### ISSUE TITLE
Gradle sync failed using android studio

### ISSUE THREAD

**Issue by ltramart** [scriptotek/nfcbookscanner#3]
Hello,

I'm quite new to Android Studio, I downloaded your project, but i am unable to compile it :-(

I get this error:
21:50:46 Gradle sync started
21:51:02 Gradle sync failed: Configuration with name 'default' not found.
         Consult IDE log for more details (Help | Show Log)

Can you help?

Thanks,
Ludovic.

**Comment by danmichaelo** [comment]
Sorry, I cannot help with Android Studio / Gradle. I haven't used it for a year or so.. Let me know if you figure it out.
